org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

publish.modrinth=
publish.curseforge=
publish.github=true


deps.voicechat_api_version=2.6.0
deps.voice_chat=2.6.16
deps.gemini_live_lib_version=2.4.1
deps.yacl_version=3.6.6
# Talking Colonists 2.1 is the first release with ApiFeature feature detection.
deps.talking_colonists_version=2.1.0-beta.1
